language: python
python:
    - "3.8"
install:
    - pip install coveralls
    - pip install -r requirements.txt
script:
    # run tests with coverage
    - coverage run -m unittest discover
after_success:
    # upload reports to coveralls.io
    - coveralls
