title: btclib
description: A Python library for 'bitcoin cryptography'.
logo: img/btclib-logo-80.jpg

show_downloads: false
github:
  owner_url: https://github.com/fametrano
  owner_name: Ferdinando Ametrano

google_analytics:

theme: jekyll-theme-minimal
